### ISSUE TITLE
Needs email address

### ISSUE THREAD

**Issue by ansonschall** [loganmoseley/loganmoseley.github.com#1]
I wasn't able to find your email address on the site. This makes it difficult for people to contact you.

**Comment by loganmoseley** [comment]
# 🤜🏽🔻…………🙌🏽
# 👉🏽…🔺………🙌🏽
# 👉🏽……🔻……🙌🏽
# 👉🏽………🔺…🙌🏽
# 👉🏽…………🔻🙌🏽
# 👉🏽……………🙌🏽🔻
# 🤙🏽……………🙌🏽…🔺
# GOOOOOOOOOOOOOOOOOOL
